name: Aternos 24/7 AFK Bot

on:
  push:
  schedule:
    - cron: '*/30 * * * *' # Սա ամեն 30 րոպեն մեկ ավտոմատ կթարմացնի բոտը, որ սերվերը չանջատվի

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Start Minecraft Bot
        uses: Minionguyjpro/Afk-bot@v1.0.3
        with:
          ip: 'ձեր_սերվերի_ip.aternos.me' # Փոխեք սա ձեր իրական Aternos IP-ով
          port: 25565                     # Փոխեք, եթե ձեր պորտը տարբեր է
          name: 'GitHub_AFK_Bot'          # Բոտի անունը խաղի մեջ
          auto-night-skip: false
